# Generated by Django 4.2.27 on 2025-12-26 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobAdvertisement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('job_type', models.CharField(choices=[('On-site', 'On-site'), ('Remote', 'Remote'), ('Hybrid', 'Hybrid'), ('Not Applicable', 'Not Applicable')], max_length=100)),
                ('company_name', models.CharField(max_length=255)),
                ('employment_type', models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Contract', 'Contract'), ('Internship', 'Internship'), ('Temporary', 'Temporary'), ('Volunteer', 'Volunteer'), ('Other', 'Other')], max_length=100)),
                ('experience_level', models.CharField(choices=[('Entry Level', 'Entry Level'), ('Mid Level', 'Mid Level'), ('Senior Level', 'Senior Level'), ('Director', 'Director'), ('Executive', 'Executive'), ('Internship', 'Internship'), ('Not Applicable', 'Not Applicable')], max_length=100)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('skills', models.TextField(blank=True, max_length=1000, null=True)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_advertisements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'job_advertisements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('portfolio_url', models.URLField(blank=True, null=True)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('cover_letter', models.TextField(blank=True, max_length=2000, null=True)),
                ('status', models.CharField(choices=[('Applied', 'Applied'), ('Under Review', 'Under Review'), ('Interview Scheduled', 'Interview Scheduled'), ('Offer Extended', 'Offer Extended'), ('Rejected', 'Rejected')], default='Applied', max_length=100)),
                ('job_advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='application_tracking.jobadvertisement')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
